#通用配置，注册中心、安全信息、rabbitmq
#测试：http://config:8880/common/dev
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB # 上传一个文件最大值,默认1Mb
      max-request-size: 3000MB # 上传多个文件最大值,50Mb,默认10Mb
  security:
    user:
      name: ${SERVER_USERNAME:user}
      password: ${SERVER_PASSWORD:password}
      roles: ${SERVER_SUPERUSER:SUPERUSER}
  rabbitmq:
    host: ${RABBITMQ_SERVER:172.16.10.87}
    port: ${RABBITMQ_SERVER_PORT:5672}
    username: ${RABBITMQ_SERVER_USERNAME:admin}
    password: ${RABBITMQ_SERVER_PASSWORD::123456}
  cloud:
    config:
      failFast: true
      retry:
        max-interval: 2000
        multiplier: 1.1
        initial-interval: 1000
        max-attempts: 6
      bus:
        trace:
          enabled: true
    inetutils:
      ignoredInterfaces:
      - lo
      - eth0
      - eth1

eureka:
  instance:
    hostname: ${eureka.instance.ip-address:${spring.cloud.client.ip-address}}
    instance-id: ${spring.application.name}:${eureka.instance.ip-address:${spring.cloud.client.ip-address}}:${server.port}
    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    metadata-map:
      zone: ${zone.name}
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    #地区
    region: beijing
    availability-zones:
      beijing: zone-1,zone-2
    service-url:
      zone-1: http://${REGISTRY_SERVER_USERNAME:user}:${REGISTRY_SERVER_PASSWORD:password}@${REGISTRY_SERVER1:peer1}:${REGISTRY_SERVER1_PORT:8761}/eureka/
      zone-2: http://${REGISTRY_SERVER_USERNAME:user}:${REGISTRY_SERVER_PASSWORD:password}@${REGISTRY_SERVER2:peer2}:${REGISTRY_SERVER2_PORT:8762}/eureka/

management:
  # 设置端点是否可用 默认只有shutdown可用
  enabled-by-default: true
  endpoints:
    web:
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # 包括所有端点
        include: '*'  # 注意需要添加引号
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      enabled: true #可在线查看日志
    shutdown:
      enabled: true #客户端开启停止服务端点
      sensitive: true  #禁用密码验证
  security:
    enabled: false #SpringBoot 1.5以后的版本都默认开启端点保护

encrypt:
  keyStore:
    location: classpath:/server.jks # jks文件的路径
    password: letmein               # storepass
    alias: mytestkey                # alias
    secret: changeme                # keypass

#logging:
#  level:
#    root: INFO
#    com:
#      netflix:
#        eureka: 'off'
#        discovery:  'off'
# INFO ENDPOINT CONFIGURATION
info:
  app:
    name: ${spring.application.name}
    java:
      version: ${java.version}
